// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 9.1.0
// Project name: Teensy41_800x400_dual_CAN

#ifndef _TEENSY41_800X400_DUAL_CAN_UI_H
#define _TEENSY41_800X400_DUAL_CAN_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
  #if __has_include("lvgl.h")
    #include "lvgl.h"
  #elif __has_include("lvgl/lvgl.h")
    #include "lvgl/lvgl.h"
  #else
    #include "lvgl.h"
  #endif
#else
  #include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_events.h"

// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
extern lv_obj_t *ui_Screen1;
void ui_event_Button1( lv_event_t * e);
extern lv_obj_t *ui_Button1;
extern lv_obj_t *ui_Spinner1;
extern lv_obj_t *ui_Switch1;
extern lv_obj_t *ui_Label1;
void ui_event_Button2( lv_event_t * e);
extern lv_obj_t *ui_Button2;
extern lv_obj_t *ui_Label2;
extern lv_obj_t *ui_Label3;
extern lv_obj_t *ui_Label4;
extern lv_obj_t *ui_Label5;
extern lv_obj_t *ui_version;
extern lv_obj_t *ui_Label6;
extern lv_obj_t *ui_coord;
extern lv_obj_t *ui_framecount;
extern lv_obj_t *ui_Slider1;
extern lv_obj_t *ui_Switch2;
extern lv_obj_t *ui_Button3;
extern lv_obj_t *ui_Button4;
extern lv_obj_t *ui_Label7;
extern lv_obj_t *ui_Label8;
extern lv_obj_t *ui____initial_actions0;





void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
