// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 9.1.0
// Project name: Teensy41_800x400_dual_CAN

#include "ui.h"
extern bool set_can_start;
void can_stop(lv_event_t * e)
{
	 set_can_start = 0;
}

void can_start(lv_event_t * e)
{
	 set_can_start = 1;
}
