// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 9.1.0
// Project name: Teensy41_800x400_dual_CAN

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void can_stop(lv_event_t * e);
void can_start(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
